COL_exp1 = ["faces",
            "size_w",
            "spacing_in_deg",
            "setsize",
            "n",
            "stim_length",
            "key_resp.keys",
            "blockOrder",
            "participant",
            "blocks.thisN",
            "blocks.thisIndex",
            "trials.thisN",
            "trials.thisIndex"]

COL_exp1_discri = ["faces",
                   "size_w",
                   "setsize",
                   "key_resp.keys",
                   "participant",
                   "blocks.thisN",
                   "blocks.thisIndex",
                   "trials.thisN",
                   "trials.thisIndex"]

COL_exp2 = ["faces",
            "size_w",
            "spacing_in_deg",
            "setsize",
            "n",
            "stim_length",
            "key_resp.keys",
            "order",
            "participant",
            "blocks.thisN",
            "blocks.thisIndex",
            "trials.thisN",
            "trials.thisIndex",
            "key_resp_7.keys",
            "is_face_usd"]

COL_exp2_discri = ["faces",
                   "size_w",
                   "setsize",
                   "key_resp.keys",
                   "order",
                   "participant",
                   "blocks.thisN",
                   "blocks.thisIndex",
                   "trials.thisN",
                   "trials.thisIndex",
                   "key_resp_7.keys",
                   "n"]